// Adapted from selected AiRA code; see docs/HARNESS.md.
import type { StatementSpec } from "./openui-model.js";
export const OPENUI_LIBRARY = {
  Screens: { args: ["screens", "cursor"], required: 1, childArg: "screens" },
  Screen: { args: ["children", "seen"], required: 1, childArg: "children" },
  Text: { args: ["text", "variant", "color"], required: 1 },
  Keyword: { args: ["text", "caption", "color"], required: 1 },
  List: { args: ["items"], required: 1, childArg: "items" },
  ListItem: { args: ["text", "marker"], required: 1 },
  Alert: { args: ["tone", "text"], required: 2 },
  Timer: { args: ["label", "seconds", "image"], required: 2 },
  Cue: { args: ["text"], required: 1 },
  FollowUps: { args: ["prompts"], required: 1 },
  PostureFocus: { args: ["posture", "colorTone"], required: 1 },
  BreathingPacer: { args: ["label", "seconds"], required: 1 },
  NeckRollGuide: { args: [], required: 0 },
  StandingGuide: { args: [], required: 0 },
  ShoulderShrugGuide: { args: [], required: 0 },
  TorsoTwistGuide: { args: [], required: 0 },
  PelvicTiltGuide: { args: [], required: 0 },
  KneeChestGuide: { args: [], required: 0 },
  LegExtensionGuide: { args: [], required: 0 },
  FigureFourGuide: { args: [], required: 0 },
  HeelToeGuide: { args: [], required: 0 },
  HandWristGuide: { args: [], required: 0 },
  SeatedMarchGuide: { args: [], required: 0 },
  TricepsLatGuide: { args: [], required: 0 },
  RhomboidPressGuide: { args: [], required: 0 },
  OverheadSideBendGuide: { args: [], required: 0 },
  AnklePumpGuide: { args: [], required: 0 },
  AnkleCircleGuide: { args: [], required: 0 },
  ToeTapGuide: { args: [], required: 0 },
  DeskPushUpGuide: { args: [], required: 0 },
  ChairSquatGuide: { args: [], required: 0 },
  LungCapacityGame: { args: [], required: 0 },
  EnergyMeter: { args: [], required: 0 },
  CalendarBanner: { args: [], required: 0 },
  AudioCoachToggle: { args: [], required: 0 },
  ThemeToggle: { args: ["mode"], required: 0 },
} as const satisfies Record<string, StatementSpec>;
